# travis build for k3b-geoHelper
language: android
android:
  components:
    - build-tools-22.0.1
    - android-19
    - add-on
    - extra

before_install:
# http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
 - chmod +x gradlew
 
script:
  - ./gradlew check assemble reports

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
